services:
  - type: web
    name: sistema-alumnos
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alumnos_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: RENDER
        value: true
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.console.EmailBackend
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: alumnos_db
    plan: free
    databaseName: alumnos
    user: alumnos_user